### ISSUE TITLE
Bad aspect ratio in README plots is disconcerting

### ISSUE THREAD

**Issue by hadley** [mdsumner/ozplot#11]
Is it possible to make the examples use a decent default projection?

**Comment by mdsumner** [comment]
It can, I just wanted the simplest possible code and to be like the maps package. I consider this a utility not an end product, but I take your point.

**Comment by mdsumner** [comment]
Now uses the inverse-cosine-latitude default for longlat data, otherwise 1. Can be overridden or unset in the usual base way: 

``` r
library(ozmaps)
#> Loading required package: tibble
ozmap()
```

![](https://i.imgur.com/JKCYL2O.png)

``` r
ozmap(asp = "")
```

![](https://i.imgur.com/gDhow3M.png)

``` r
ozmap(asp = 2)
```

![](https://i.imgur.com/lIB56eo.png)

<sup>Created on 2019-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks!

**Comment by hadley** [comment]
That looks way better — thanks!
